#Kütüphane Ekleme

In [146]:
import numpy as np

In [147]:
import pandas as pd

#numpy

Tek boyutlu int array oluşturma

In [103]:
a=np.array([1,2,3,4,5,6,7,8,9,10],dtype="int")
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

İki boyutlu array oluşturma

In [104]:
b=np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

20 iel 100 arasında ikişer aralıklı doğrusal bir numpy array oluşturma

In [105]:
c=np.arange(20,100,2)
c

array([20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50, 52,
       54, 56, 58, 60, 62, 64, 66, 68, 70, 72, 74, 76, 78, 80, 82, 84, 86,
       88, 90, 92, 94, 96, 98])

Rastgele değerlerden oluşan 4*5 lik numpy array oluşturma

In [106]:
d=np.random.random((4,5))
d

array([[0.68839439, 0.82981328, 0.25064479, 0.23279866, 0.22322703],
       [0.35012703, 0.85294991, 0.2126749 , 0.00561238, 0.29746371],
       [0.88588433, 0.84404871, 0.83578718, 0.75251376, 0.00430171],
       [0.96630587, 0.0766124 , 0.88122732, 0.04264294, 0.87730564]])

0 ile 100 arasında rastgele değerlerden oluşan 4*10 numpy array oluşturma

In [107]:
e=np.random.randint(0,100,size=(4,10))
e

array([[93, 18, 19, 31, 18, 17, 96, 58,  4, 42],
       [27, 67, 38, 27, 93, 54, 76, 12, 17,  6],
       [66, 11, 21, 22, 89, 34, 80, 29, 30, 57],
       [91, 54, 68, 65, 55, 29, 20, 67, 52, 53]])

Array boyutu
Eleman sayısı
Tipi

In [108]:
e.ndim

2

In [109]:
e.shape

(4, 10)

In [110]:
e.size

40

In [111]:
e.dtype

dtype('int32')

Tek boyutlu arrayi iki boyuta döndürme

In [112]:
f=a.reshape((2,5))
f

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

iki tek boyutlu arrayi birleştirme

In [113]:
array1=np.array([1,2,3])
array2=np.array([4,5,6])
birlesim=np.concatenate([array1,array2])
birlesim

array([1, 2, 3, 4, 5, 6])

iki tane 3*5 lik array oluşturma ve sütun birleştirme

In [114]:
x=np.random.random((3,5))
y=np.random.random((3,5))
z=np.concatenate([x,y],axis=1)
z

array([[0.08323269, 0.0287011 , 0.34468329, 0.61149471, 0.28366683,
        0.15734896, 0.6316486 , 0.56667581, 0.93276001, 0.78502938],
       [0.42004957, 0.95138878, 0.42132373, 0.74861654, 0.37812646,
        0.61021747, 0.32434405, 0.66773373, 0.36794025, 0.43259952],
       [0.96916948, 0.2876765 , 0.61718395, 0.75903467, 0.8134386 ,
        0.31209551, 0.48559671, 0.96073688, 0.09614709, 0.39709138]])

Tek boyutlu arrayi 3 parçaya, iki boyutlu arrayi dikeyde 2 parçaya ayırma

In [115]:
j,k,l=np.split(z,[2,4])
j
k
l

array([], shape=(0, 10), dtype=float64)

In [116]:
i,p=np.hsplit(z,[3])
i
p

array([[0.61149471, 0.28366683, 0.15734896, 0.6316486 , 0.56667581,
        0.93276001, 0.78502938],
       [0.74861654, 0.37812646, 0.61021747, 0.32434405, 0.66773373,
        0.36794025, 0.43259952],
       [0.75903467, 0.8134386 , 0.31209551, 0.48559671, 0.96073688,
        0.09614709, 0.39709138]])

Tek boyutlu arrayin içindeki bir elemanı değerini değiştirme

In [117]:
a[1]=7
a

array([ 1,  7,  3,  4,  5,  6,  7,  8,  9, 10])

İki boyutlu arraylarden birinin içindeki elemanı değiştirme

In [118]:
b[1,1]=5
b

array([[1, 2, 3],
       [4, 5, 6]])

5*10 rastgele array oluşturma

In [119]:
rs=np.random.randint(0,20,size=(5,10))
rs

array([[11, 12,  9,  9, 12, 16,  5,  6, 10,  9],
       [19, 16,  5,  4,  2, 13, 18,  6, 16, 14],
       [ 8, 16, 11, 18, 19,  0, 16, 10,  8, 19],
       [19,  4,  8, 10, 15,  9,  6, 15, 18, 16],
       [ 8,  9,  9, 17, 19,  4, 12, 17, 17, 17]])

Arrayin içerisinden 0-4e kadar satırları 1-5e kadar sutunları alma

In [120]:
o=rs[:4,1:5]
o

array([[12,  9,  9, 12],
       [16,  5,  4,  2],
       [16, 11, 18, 19],
       [ 4,  8, 10, 15]])

Tek boyutlu bir arrayin elemanlarının 5 ten küçük olanlarına erişme

In [121]:
a[a<5]

array([1, 3, 4])

Pandas

6 elemanlı bir seri oluşturma

In [122]:
pd=pd.Series([1,2,3,4,5,6], index=["a","b","c","d","e","f"])
pd

a    1
b    2
c    3
d    4
e    5
f    6
dtype: int64

serinin index ve value lerini getirme

In [123]:
pd.axes

[Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')]

In [124]:
pd.values

array([1, 2, 3, 4, 5, 6], dtype=int64)

Serinin ikinci elemanı çağırma ve ikiden beşe kadar olanlarını çağırma

In [125]:
pd[2]

3

In [126]:
pd[2:5]

c    3
d    4
e    5
dtype: int64

serinin 0,204. elemanlarını fancy ile çağırma

In [143]:
pd[[0,2,4]]

a    1
c    3
e    5
dtype: int64

3*3 numpy array oluşturma ve dataframe e çevirip sütun isimlerini değiştirme

In [144]:
newpd=np.random.randint(0,20,size=(10,3))
newpd

array([[ 9, 16,  1],
       [15,  6,  1],
       [16,  9,  8],
       [ 4,  9,  7],
       [16,  1,  1],
       [18, 15,  8],
       [14, 13, 14],
       [ 4,  4, 19],
       [ 3,  4,  2],
       [11,  7,  9]])

In [148]:
v=pd.DataFrame(newpd,columns=["a","b","c"])
v

a   b   c
0   9  16   1
1  15   6   1
2  16   9   8
3   4   9   7
4  16   1   1
5  18  15   8
6  14  13  14
7   4   4  19
8   3   4   2
9  11   7   9

ilk 5 elemanını getirme

In [150]:
v.head()

a   b  c
0   9  16  1
1  15   6  1
2  16   9  8
3   4   9  7
4  16   1  1

Datafrme in ikinci satırını kalıcı olarak silme:

In [151]:
v.drop(1, axis=0, inplace = True)
v

a   b   c
0   9  16   1
2  16   9   8
3   4   9   7
4  16   1   1
5  18  15   8
6  14  13  14
7   4   4  19
8   3   4   2
9  11   7   9

Yeni bir sütun oluşturup bu sütuna ilk üç sütunun çapım değerlerini atama:

In [155]:
v["d"] = v["a"]*v["b"]*v["c"]
v

a   b   c     d
0   9  16   1   144
2  16   9   8  1152
3   4   9   7   252
4  16   1   1    16
5  18  15   8  2160
6  14  13  14  2548
7   4   4  19   304
8   3   4   2    24
9  11   7   9   693

In [156]:
Oluşan dataframe i bozulan indexleri düzelterek birleştirme: 

SyntaxError: invalid syntax (460995195.py, line 1)

In [157]:
v1=pd.concat([v,v], ignore_index=True)
v1

a   b   c     d
0    9  16   1   144
1   16   9   8  1152
2    4   9   7   252
3   16   1   1    16
4   18  15   8  2160
5   14  13  14  2548
6    4   4  19   304
7    3   4   2    24
8   11   7   9   693
9    9  16   1   144
10  16   9   8  1152
11   4   9   7   252
12  16   1   1    16
13  18  15   8  2160
14  14  13  14  2548
15   4   4  19   304
16   3   4   2    24
17  11   7   9   693

ilk iki değişkenin 3 satırını getirme

In [158]:
v1.iloc[:3,:2]

a   b
0   9  16
1  16   9
2   4   9